
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;

	private global::Gtk.Table table3;

	private global::Gtk.Button button1;

	private global::Gtk.Button button2;

	private global::Gtk.Button button3;

	private global::Gtk.Button button4;

	private global::Gtk.Button button5;

	private global::Gtk.Button button6;

	private global::Gtk.Button button7;

	private global::Gtk.Button button8;

	private global::Gtk.Button button9;

	private global::Gtk.Entry entry1;

	private global::Gtk.Button button11;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("Крестики-нолики");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.table3 = new global::Gtk.Table(((uint)(3)), ((uint)(3)), true);
		this.table3.Name = "table3";
		this.table3.RowSpacing = ((uint)(6));
		this.table3.ColumnSpacing = ((uint)(6));
		// Container child table3.Gtk.Table+TableChild
		this.button1 = new global::Gtk.Button();
		this.button1.CanFocus = true;
		this.button1.Name = "button1";
		this.button1.UseUnderline = true;
		this.table3.Add(this.button1);
		// Container child table3.Gtk.Table+TableChild
		this.button2 = new global::Gtk.Button();
		this.button2.CanFocus = true;
		this.button2.Name = "button2";
		this.button2.UseUnderline = true;
		this.table3.Add(this.button2);
		global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table3[this.button2]));
		w2.LeftAttach = ((uint)(1));
		w2.RightAttach = ((uint)(2));
		// Container child table3.Gtk.Table+TableChild
		this.button3 = new global::Gtk.Button();
		this.button3.CanFocus = true;
		this.button3.Name = "button3";
		this.button3.UseUnderline = true;
		this.table3.Add(this.button3);
		global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table3[this.button3]));
		w3.LeftAttach = ((uint)(2));
		w3.RightAttach = ((uint)(3));
		// Container child table3.Gtk.Table+TableChild
		this.button4 = new global::Gtk.Button();
		this.button4.CanFocus = true;
		this.button4.Name = "button4";
		this.button4.UseUnderline = true;
		this.table3.Add(this.button4);
		global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table3[this.button4]));
		w4.TopAttach = ((uint)(1));
		w4.BottomAttach = ((uint)(2));
		// Container child table3.Gtk.Table+TableChild
		this.button5 = new global::Gtk.Button();
		this.button5.CanFocus = true;
		this.button5.Name = "button5";
		this.button5.UseUnderline = true;
		this.table3.Add(this.button5);
		global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table3[this.button5]));
		w5.TopAttach = ((uint)(1));
		w5.BottomAttach = ((uint)(2));
		w5.LeftAttach = ((uint)(1));
		w5.RightAttach = ((uint)(2));
		// Container child table3.Gtk.Table+TableChild
		this.button6 = new global::Gtk.Button();
		this.button6.CanFocus = true;
		this.button6.Name = "button6";
		this.button6.UseUnderline = true;
		this.table3.Add(this.button6);
		global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table3[this.button6]));
		w6.TopAttach = ((uint)(1));
		w6.BottomAttach = ((uint)(2));
		w6.LeftAttach = ((uint)(2));
		w6.RightAttach = ((uint)(3));
		// Container child table3.Gtk.Table+TableChild
		this.button7 = new global::Gtk.Button();
		this.button7.CanFocus = true;
		this.button7.Name = "button7";
		this.button7.UseUnderline = true;
		this.table3.Add(this.button7);
		global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table3[this.button7]));
		w7.TopAttach = ((uint)(2));
		w7.BottomAttach = ((uint)(3));
		// Container child table3.Gtk.Table+TableChild
		this.button8 = new global::Gtk.Button();
		this.button8.CanFocus = true;
		this.button8.Name = "button8";
		this.button8.UseUnderline = true;
		this.table3.Add(this.button8);
		global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table3[this.button8]));
		w8.TopAttach = ((uint)(2));
		w8.BottomAttach = ((uint)(3));
		w8.LeftAttach = ((uint)(1));
		w8.RightAttach = ((uint)(2));
		// Container child table3.Gtk.Table+TableChild
		this.button9 = new global::Gtk.Button();
		this.button9.CanFocus = true;
		this.button9.Name = "button9";
		this.button9.UseUnderline = true;
		this.table3.Add(this.button9);
		global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table3[this.button9]));
		w9.TopAttach = ((uint)(2));
		w9.BottomAttach = ((uint)(3));
		w9.LeftAttach = ((uint)(2));
		w9.RightAttach = ((uint)(3));
		this.vbox1.Add(this.table3);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.table3]));
		w10.Position = 0;
		// Container child vbox1.Gtk.Box+BoxChild
		this.entry1 = new global::Gtk.Entry();
		this.entry1.CanFocus = true;
		this.entry1.Name = "entry1";
		this.entry1.IsEditable = true;
		this.entry1.InvisibleChar = '●';
		this.vbox1.Add(this.entry1);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.entry1]));
		w11.Position = 1;
		w11.Expand = false;
		w11.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.button11 = new global::Gtk.Button();
		this.button11.CanFocus = true;
		this.button11.Name = "button11";
		this.button11.UseUnderline = true;
		this.button11.Label = global::Mono.Unix.Catalog.GetString("Начать заново");
		this.vbox1.Add(this.button11);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.button11]));
		w12.Position = 2;
		w12.Expand = false;
		w12.Fill = false;
		this.Add(this.vbox1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 472;
		this.DefaultHeight = 300;
		this.Show();
		this.button9.Clicked += new global::System.EventHandler(this.ClickTicTacToeButton);
		this.button8.Clicked += new global::System.EventHandler(this.ClickTicTacToeButton);
		this.button7.Clicked += new global::System.EventHandler(this.ClickTicTacToeButton);
		this.button6.Clicked += new global::System.EventHandler(this.ClickTicTacToeButton);
		this.button5.Clicked += new global::System.EventHandler(this.ClickTicTacToeButton);
		this.button4.Clicked += new global::System.EventHandler(this.ClickTicTacToeButton);
		this.button3.Clicked += new global::System.EventHandler(this.ClickTicTacToeButton);
		this.button2.Clicked += new global::System.EventHandler(this.ClickTicTacToeButton);
		this.button1.Clicked += new global::System.EventHandler(this.ClickTicTacToeButton);
		this.button11.Clicked += new global::System.EventHandler(this.OnButton10Clicked);
	}
}
